##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Makefile
##

all:
	make -C asm/

clean:
	make -C asm/ clean

fclean:		clean
	make -C asm/ fclean

re: fclean all

.PHONY: clean fclean re
