version: '3'
services:
    poll:
        build: ./poll
        depends_on:
            - "redis"
        ports:
            - "5000:80"
        networks:
            - poll-tier

    redis:
        image: "redis:latest"
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - poll-tier
            - back-tier

    worker:
        build: ./worker
        depends_on:
            - "db"
        networks:
            - back-tier

    db:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data
        networks:
            - result-tier
            - back-tier

    result:
        build: ./result
        ports:
            - "5001:80"
        depends_on:
            - "db"
        networks:
            - result-tier

volumes:
    db-data:

networks:
    poll-tier:
    result-tier:
    back-tier:
