---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: worker
  namespace: default
  labels:
    app: my_app
    my_app: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my_app
      task: worker
  template:
    metadata:
      labels:
        app: my_app
        task: worker
    spec:
      containers:
      - name: my_app
        image: epitechcontent/t-dop-600-worker:k8s
        env:
        - name: REDIS_HOST
          value: "re_host"
        - name: POSTGRES_HOST
          value: "re_host"
        - name: POSTGRES_PORT
          value: "pg_port"
        - name: POSTGRES_DB
          value: "pg_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresDb
              key: pg_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresDb
              key: pg_pass
        resources:
          limits:
            memory: 256Mi
      restartPolicy: Always
